#!/bin/sh

 # Ask the user for login details

git status

echo "What files would you like to add"
read addFiles

echo "Enter your commit message"
read commitMessage

echo set wait for 3 seconds before commit
  sleep 3

git add $addFiles

git commit -m "$commitMessage"

#notify-send "-i <icon> <Message>"
notify-send -i face-wink "Dont Forget To Push"
