#!/bin/sh

 # Ask the user for login details

git status

echo "What files would you like to add"
read fn

echo "Enter your commit message"
read say

echo set wait for 3 seconds before commit
  sleep 3

git add $fn

git commit -m "$say"


#notify-send "-i <icon> <Message>"
notify-send -i face-wink "Dont Forget To Push"
