#!/bin/bash
    #!/bin/bash
    # Ask the user for login details
  
   git status 
    

echo "Fill what you want to add"
read fn
sleep 3

echo "commit massage"

read say

git add $fn

git status


git commit -m "$say"
