#!/bin/bash
    #!/bin/bash
    # Ask the user for login details
  
   git status 
    

echo "Fill what you want to add"
read fn
sleep 3
git add $fn

git status

echo "commit massage"

read say

git commit -m "$say"
