#!/bin/bash
    #!/bin/bash
    # Ask the user for login details
  
   git status 
    

echo "Fill what you want to add"
read fn


echo "commit massage"
read say

sleep 9


git add $fn

git commit -m "$say"
